Feature/hooks
Gnwin/math-magicians pull request #4
Opened 2022-04-30 12:19 UTC by Gnwin

## Math Magicians: Refactor with hooks

In this milestone, the logic of the application was converted to stateful functional components with react hooks without without any errors. All requirements for this milestone have been met according to this document:

https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_refactor_with_hooks.md

2022-04-30 12:25 UTC, GzimAsani requested changes
### Hi @Gnwin     
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Your code organization is good.
 
 ## Required Changes 
 - Please explain better(in more detail) the steps that a user should take in order to clone and run your project




 _Check the comments under the review._
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 12:25 UTC, GzimAsani commented on src/reactjs/components/Calculator.js
> -      calcData = calculate(this.state, buttonContent);
- [ ] The calculator component should also be refactored similar to app.js

2022-04-30 12:25 UTC, GzimAsani commented on README.md
> +- Run `git checkout feature/hooks` to switch to develop branch
- [ ] You have some merging conflict, please resolve it. I think the conflict comes from readme file

2022-05-01 04:02 UTC, Meltrust approved these changes
Hi @Gnwin,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for refactoring your Calculator component, and for solving the readme issue, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-01 04:22 UTC, Gnwin commented
Thanks @Meltrust

2022-05-01 04:22 UTC, merged